name:                nbe
version:             0.1.0.0
github:              "githubuser/nbe"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/nbe#readme>

dependencies:
- base >= 4.7 && < 5
- bound
- unordered-containers
- bytestring
- containers
- diagnose
- transformers
- generic-lens
- text
- vector
- attoparsec
- parsers
- megaparsec
- parser-combinators
- deriving-compat
- type-natural
- rio
- mtl
- lens
- ghc-typelits-presburger
- equational-reasoning
- hashable
- unordered-containers
- bifunctors
- split
- semigroups

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  nbe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nbe
