name:                lambda-pi
version:             0.1.0.0
github:              "konn/lambda-pi"
license:             BSD3
author:              "Hiromi ISHII"
maintainer:          "konn.jinro_at_gmail.com"
copyright:           "(c) 2022- Hiromi ISHII"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/konn/lambda-pi#readme>

dependencies:
- base >= 4.7 && < 5
- algebraic-graphs
- attoparsec
- bifunctors
- bytestring
- containers
- dependent-sum
- dependent-map
- deriving-compat
- diagnose
- dlist
- either
- filtrable
- these
- equational-reasoning
- fmlist
- generic-lens
- generic-deriving
- ghc-typelits-presburger
- hashable
- haskeline
- lens
- megaparsec
- mmorph
- monad-loops
- mtl
- parser-combinators
- parsers
- pretty
- rio
- rio-orphans
- semialign
- semigroups
- semigroupoids
- some
- split
- template-haskell
- text
- transformers
- type-natural
- unordered-containers
- vector

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  lambda-pi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-pi

tests:
  lambda-pi-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - tasty-discover
    dependencies:
    - lambda-pi
    - dlist
    - falsify
    - selective
    - tasty
    - tasty-hunit
    - tasty-quickcheck
