on: push
name: Build and Test

env:
  CABAL: cabal --project-file=cabal-ci.project

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set file hash
      run: |
        echo "FILE_HASH=${{hashFiles('**/*.hs')}}" >> ${GITHUB_ENV}
    - name: Restore ~/.cabal/store
      uses: actions/cache/restore@v3
      with:
        path: ~/.cabal/store
        key: |
          ubuntu-9.2.8-cabal-store-${{hashFiles('cabal.project.freeze')}}-${{ hashFiles('package.yaml', '**/*.cabal') }}-${{github.sha}}
        restore-keys: |
          ubuntu-9.2.8-cabal-store-${{hashFiles('cabal.project.freeze')}}-${{ hashFiles('package.yaml', '**/*.cabal') }}-
          ubuntu-9.2.8-cabal-store-${{hashFiles('cabal.project.freeze')}}-
          ubuntu-9.2.8-cabal-store-

    - name: Restore ./dist-newstyle
      uses: actions/cache/restore@v3
      with:
        path: dist-newstyle
        key: |
          ubuntu-9.2.8-dist-newstyle-${{hashFiles('cabal.project.freeze')}}-${{ hashFiles('package.yaml', '**/*.cabal') }}-${{ env.FILE_HASH }}-${{github.sha}}
        restore-keys: |
          ubuntu-9.2.8-dist-newstyle-${{hashFiles('cabal.project.freeze')}}-${{ hashFiles('package.yaml', '**/*.cabal') }}-${{ env.FILE_HASH }}-
          ubuntu-9.2.8-dist-newstyle-${{hashFiles('cabal.project.freeze')}}-${{ hashFiles('package.yaml', '**/*.cabal') }}-
          ubuntu-9.2.8-dist-newstyle-${{hashFiles('cabal.project.freeze')}}-
          ubuntu-9.2.8-dist-newstyle-
    - name: Setup Haskell
      uses: haskell/actions/setup@v2
      with:
        cabal-version: 3.10.1.0
        ghc-version: 9.2.8
    - run: cabal update
    - name: Build dependencies
      run: |
        ${CABAL} build --only-dependencies all

    - name: Save ~/.cabal/store
      uses: actions/cache/save@v3
      with:
        path: ~/.cabal/store
        key: |
          ubuntu-9.2.8-cabal-store-${{hashFiles('cabal.project.freeze')}}-${{ hashFiles('package.yaml', '**/*.cabal') }}-${{github.sha}}

    - name: Build All
      id: build
      run: ${CABAL} build all

    - name: Save ./dist-newstyle
      if: ${{ steps.build.conclusion == 'success' }}
      uses: actions/cache/save@v3
      with:
        path: dist-newstyle
        key: |
          ubuntu-9.2.8-dist-newstyle-${{hashFiles('cabal.project.freeze')}}-${{ hashFiles('package.yaml', '**/*.cabal') }}-${{ env.FILE_HASH }}-${{github.sha}}

  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Setup Haskell
      uses: haskell/actions/setup@v2
      with:
        cabal-version: 3.10.1.0
        ghc-version: 9.2.8
    - name: Restore ~/.cabal/store
      uses: actions/cache/restore@v3
      with:
        path: ~/.cabal/store
        key: |
          ubuntu-9.2.8-cabal-store-${{hashFiles('cabal.project.freeze')}}-${{ hashFiles('package.yaml', '**/*.cabal') }}-${{github.sha}}
        fail-on-cache-miss: true
    - name: Restore Test Cache
      uses: actions/cache/restore@v3
      with:
        key: |
          ubuntu-9.2.8-dist-newstyle-${{hashFiles('cabal.project.freeze')}}-${{ hashFiles('package.yaml', '**/*.cabal') }}-${{ hashFiles('**/*.hs') }}-${{github.sha}}
        path: dist-newstyle
        fail-on-cache-miss: true
    - name: Run Tests
      run: cabal test all
